codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 60%
        threshold: 1%
        informational: false

      # Core business logic library - maintain high standards
      library:
        target: 80%
        threshold: 1%
        paths:
          - "WinterAdventurer.Library/**"
        informational: false

      # Blazor web app - more lenient for UI code
      web-app:
        target: 30%
        threshold: 2%
        paths:
          - "WinterAdventurer/**"
        informational: true

    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore generated files and test files from coverage
ignore:
  - "**/*Tests.cs"
  - "**/*Test.cs"
  - "**/obj/**"
  - "**/bin/**"
  - "**/*.g.cs"
  - "**/Migrations/**"
